name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ github.repository }}
      PACKAGE_REGISTRY: docker.pkg.github.com
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: create docker tag
      run: |
        echo ::set-env name=DOCKER_IMAGE::$(echo $PACKAGE_REGISTRY/$REPOSITORY/house-gh-webhook)
        echo ::set-env name=DOCKER_TAG::$(echo $GITHUB_SHA | cut -c1-7)
    - name: test and build
      run: |
        ./gradlew test build
    - name: Build docker image
      run: |
        docker build . -t $DOCKER_IMAGE:$DOCKER_TAG
    - name: push docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
        docker push $DOCKER_IMAGE:$DOCKER_TAG
    - name: Print version
      run: |
        echo docker_image: $DOCKER_IMAGE
        echo docker_tag: $DOCKER_TAG
